CREATE DATABASE LUMIN;
USE LUMIN;

CREATE TABLE USERS(
ID_USER INT,
USERNAME VARCHAR(15),
NAME_ VARCHAR(40),
PASSWRD VARCHAR(15),
ISADMIN TINYINT,
PRIMARY KEY(USERNAME)
);

CREATE TABLE INVENTORY(
ID_PRODUCT INT,
NAME_PRODUCT VARCHAR(40),
PRICE FLOAT,
CANT_STOCK INT,
IMG_SOURCE VARCHAR(80),
CATEGORY VARCHAR(30),
DESCRPTION VARCHAR(100),
ISAVAILABLE TINYINT,
PRIMARY KEY (ID_PRODUCT)
);

CREATE TABLE SALES(
ID_SALE INT,
USERNAME VARCHAR(15),
DATE_SOLD DATETIME,
PRIMARY KEY (ID_SALE),
FOREIGN KEY (USERNAME) REFERENCES USERS(USERNAME) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE SALES_INVENTORY(
ID_SALE INT,
ID_PRODUCT INT,
CANT_ITEMS INT,
PRIMARY KEY(ID_SALE, ID_PRODUCT),
FOREIGN KEY (ID_SALE) REFERENCES SALES(ID_SALE) ON UPDATE CASCADE ON DELETE CASCADE,
FOREIGN KEY(ID_PRODUCT) REFERENCES INVENTORY(ID_PRODUCT) ON UPDATE CASCADE ON DELETE CASCADE
);